#!/bin/bash


export PROJECTS_HOME="${HOME}/Projects"

export DOTFILES_HOME="${HOME}/.dotfiles"

# global user bin
export GLOBAL_BIN=/usr/local/bin

# java
export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"

# python
export PYTHONIOENCODING="UTF-8"
export WORKON_HOME=${HOME}/.virtualenvs
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv
if [ -f /usr/local/bin/virtualenvwrapper.sh ]; then . /usr/local/bin/virtualenvwrapper.sh; fi

# umake
export UMAKE_HOME="$HOME/.local/share/umake"

# user local bin
export USER_BIN="$HOME/.bin"
export USER_LOCAL_BIN="$HOME/.local/bin"

# go
export GOPATH=${HOME}/go

# update path
export PATH=${USER_LOCAL_BIN}:${USER_BIN}:${GLOBAL_BIN}:${PATH}:/sbin

# add go to path
export PATH=/usr/local/go/bin:${GOPATH}/bin:${PATH}

# rust
export RUST_HOME=${HOME}/.cargo

# add rust to path
export PATH=${RUST_HOME}/bin:${PATH}

# add bcc tools path
export PATH=/usr/share/bcc/tools:${PATH}

# update cdpath
export CDPATH=${CDPATH}:${GOPATH}/src/github.com:${GOPATH}/src/golang.org:${GOPATH}/src

# The next line updates PATH for the Google Cloud SDK.
# shellcheck source=/dev/null
if [ -f "${HOME}/google-cloud-sdk/path.bash.inc" ]; then . "${HOME}/google-cloud-sdk/path.bash.inc"; fi

# update path for gnu coreutils, make & find on darwin
export PATH=/usr/local/opt/coreutils/libexec/gnubin:${PATH}
export MANPATH=/usr/local/opt/coreutils/libexec/gnuman:${MANPATH}
export PATH=/usr/local/opt/make/libexec/gnubin:${PATH}
export MANPATH=/usr/local/opt/make/libexec/gnuman:${MANPATH}
export PATH=/usr/local/opt/findutils/libexec/gnubin:${PATH}
export MANPATH=/usr/local/opt/findutils/libexec/gnuman:${MANPATH}
