#!/bin/bash

# [!] Do not rename this file to `bash_completion`
#     as it will create an infinite loop!

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# The next line enables shell command completion for gcloud.
# shellcheck source=/dev/null
if [ -f "${HOME}/google-cloud-sdk/completion.bash.inc" ]; then . "${HOME}/google-cloud-sdk/completion.bash.inc"; fi

# The next line enables shell command completion for projects specific stuff.
if [ -f "${PROJECTS_HOME}/bash_completion" ]; then . "${PROJECTS_HOME}/bash_completion"; fi

