#!/bin/bash

# Bash options.
# https://www.gnu.org/software/bash/manual/bashref.html#The-Shopt-Builtin


# automatically prepend `cd` to directory names.
shopt -s autocd


# autocorrect typos in path names when using the `cd` command.
shopt -s cdspell


# check the window size after each command and, if necessary, update the values of `LINES` and `COLUMNS`.
shopt -s checkwinsize


# save all lines of a multiple-line command in the same history entry.
shopt -s cmdhist


# include filenames beginning with a "." in the filename expansion.
shopt -s dotglob


# use extended pattern matching features.
shopt -s extglob


# append to the history file rather then overwriting it.
shopt -s histappend


# do not attempt to search the PATH for possible completions when completion is attempted on an empty line.
shopt -s no_empty_cmd_completion



# match filenames in a case-insensitive fashion when performing filename expansion.
shopt -s nocaseglob
